version: 0.2
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Compiling the Java Code'
      - npx jest --listTests
      - npx jest --runInBand --coverage
      - ls
      - pwd
      - cd coverage
      - ls
  post_build:
    commands:
      - echo "Would deploy here"
