version: 0.2
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:

      - npm install jest-junit --save-dev
      - export CODEBUILD_TOTAL_SHARDS=2
      - export CODEBUILD_CURRENT_SHARD=1
      - codebuild-tests-run --test-command "npx jest" --files-search "codebuild-glob-search '_tests_/*test*'"

  post_build:
    commands:
      - echo "Would deploy here"
