version: 0.2

batch:
  fast-fail: true
  build-fanout:
    parallelism: 3
    
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:

      - npm install jest-junit --save-dev
      - codebuild-tests-run --test-command "npx jest" --files-search "codebuild-glob-search '_tests_/*test*'"

  post_build:
    commands:
      - echo "Would deploy here"
