version: 0.2

batch:
  fast-fail: true
  build-fanout:
    parallelism: 2
    
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:

      - npm install jest-junit --save-dev
      - echo $CODEBUILD_TOTAL_SHARDS
      - echo $CODEBUILD_CURRENT_SHARD
      - codebuild-tests-run --test-command "npx jest" --files-search "codebuild-glob-search '_tests_/*test*'" --sharding-strategy 'stability'

  post_build:
    commands:
      - echo "Would deploy here"
