version: 0.2
phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Compiling the Java Code'
      - codebuild-glob-search "*test*"
      - codebuild-glob-search "**/*test*"
      - npm install jest-junit --save-dev
      - codebuild-glob-search "**/*test*"
      - codebuild-tests-run --test-command "npx jest" --files-search "codebuild-glob-search '_tests_/*test*'"
      - npx jest --listTests
      - npx jest --runInBand --coverage
      - ls
      - pwd
      - cd _tests_
      - ls
  post_build:
    commands:
      - echo "Would deploy here"
